version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    env_file:
      - .env
    environment:
      - POSTGRES_URL=db
    depends_on:
      - db
    networks:
      - workerhub_net

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - workerhub_net

networks:
  workerhub_net:
    driver: bridge
