name: CI Pipeline

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python and install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag janepanov/job-offerings:1.0

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: janepanov
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push janepanov/job-offerings:1.0
